// ═══════════════════════════════════════════
// AI HUB v3 — Sabitler & Model Tanımları
// ═══════════════════════════════════════════
import type { ModelInfo, ImageModel, ThemeConfig, QuickPrompt } from '@/types';

export const PROVIDERS = [
  {
    id: 'groq',
    name: 'Groq',
    desc: 'Ultra hızlı LPU çipler. LLaMA, Mixtral, DeepSeek.',
    emoji: '⚡',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    desc: 'Tek key ile 200+ model. 25+ ücretsiz model.',
    emoji: '🔀',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    desc: 'Gemini 2.0 Flash, 2.5 Pro. 1M token context.',
    emoji: '🔮',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    desc: 'Claude Sonnet 4, Opus 4. Kod ve analizde üstün.',
    emoji: '🧠',
  },
  {
    id: 'pollinations',
    name: 'Pollinations',
    desc: 'Key gerektirmez. GPT, Mistral, LLaMA tabanlı.',
    emoji: '🌸',
  },
] as const;

export const MODELS: Record<string, ModelInfo[]> = {
  groq: [
    {
      id: 'llama-3.3-70b-versatile',
      name: 'LLaMA 3.3 70B · 280t/s',
      info: 'Meta en güçlü açık modeli. 131K ctx. Genel amaçlı.',
    },
    {
      id: 'llama-3.1-8b-instant',
      name: 'LLaMA 3.1 8B · 560t/s ⚡',
      info: 'En hızlı Groq modeli. 131K ctx. Basit görevler.',
    },
    {
      id: 'openai/gpt-oss-120b',
      name: 'GPT-OSS 120B · 500t/s ★',
      info: 'OpenAI açık ağırlıklı. 120B param. Web search + kod yürütme.',
    },
    {
      id: 'openai/gpt-oss-20b',
      name: 'GPT-OSS 20B · 1000t/s ⚡',
      info: 'GPT-OSS serisi en hızlı. 1000 t/s! 131K ctx.',
    },
    {
      id: 'meta-llama/llama-4-scout-17b-16e-instruct',
      name: 'LLaMA 4 Scout 17B · 750t/s',
      info: 'Meta LLaMA 4 ailesi. 16 uzman MoE. Çok hızlı.',
    },
    {
      id: 'qwen/qwen3-32b',
      name: 'Qwen3 32B · 400t/s',
      info: 'Alibaba Qwen3. Güçlü mantık ve kod. 131K ctx.',
    },
    {
      id: 'groq/compound',
      name: 'Groq Compound ★ Web+Kod',
      info: 'Web arama + kod yürütme dahil sistem. Otomatik araç seçimi.',
    },
    {
      id: 'groq/compound-mini',
      name: 'Groq Compound Mini ⚡',
      info: 'Compound Mini — hızlı, araç destekli sistem.',
    },
    {
      id: 'mixtral-8x7b-32768',
      name: 'Mixtral 8x7B',
      info: 'Mistral MoE. 32K ctx. Kod ve analiz.',
    },
  ],
  openrouter: [
    {
      id: 'openrouter/free',
      name: '🔀 Auto Free Router ★',
      info: 'OpenRouter ücretsiz modellerden otomatik seçer. Akıllı yönlendirme.',
    },
    {
      id: 'deepseek/deepseek-v4-flash:free',
      name: '🆓 DeepSeek V4 Flash ★',
      info: '284B MoE, 13B aktif param. 1M ctx. Hızlı, akıl yürütme destekli.',
    },
    {
      id: 'nvidia/llama-3.3-nemotron-super-49b-v1:free',
      name: '🆓 Nemotron Super 49B ★',
      info: 'NVIDIA. 1M ctx. Agentic görevler, kod, çok adımlı planlama.',
    },
    {
      id: 'qwen/qwen3-coder-480b:free',
      name: '🆓 Qwen3 Coder 480B ★Kod',
      info: 'En güçlü ücretsiz kod modeli. Agentic coding.',
    },
    {
      id: 'deepseek/deepseek-r1:free',
      name: '🆓 DeepSeek R1 ★Mantık',
      info: 'Güçlü chain-of-thought. Matematik ve analiz.',
    },
    {
      id: 'meta-llama/llama-4-maverick:free',
      name: '🆓 LLaMA 4 Maverick ★1M ctx',
      info: '1 milyon token context! LLaMA 4 büyük model.',
    },
    {
      id: 'qwen/qwen3-235b-a22b:free',
      name: '🆓 Qwen3 235B MoE ★Dev',
      info: '235B dev MoE. Çok güçlü.',
    },
    {
      id: 'meta-llama/llama-3.3-70b-instruct:free',
      name: '🆓 LLaMA 3.3 70B',
      info: 'Genel amaçlı güçlü model.',
    },
    {
      id: 'mistralai/mistral-small-3.2:free',
      name: '🆓 Mistral Small 3.2',
      info: 'Mistral güncel kompakt model.',
    },
    { id: 'google/gemma-3-27b-it:free', name: '🆓 Gemma 3 27B', info: 'Google büyük açık modeli.' },
    {
      id: 'nvidia/llama-3.3-nemotron-super:free',
      name: '🆓 Nemotron Super 49B',
      info: 'NVIDIA fine-tune. Agentic.',
    },
    {
      id: 'microsoft/phi-4-reasoning-plus:free',
      name: '🆓 Phi-4 Reasoning Plus',
      info: 'Microsoft mantık modeli. Gelişmiş akıl yürütme.',
    },
    {
      id: 'anthropic/claude-sonnet-4-5',
      name: '💳 Claude Sonnet 4.5',
      info: 'Anthropic en güncel. Üstün analiz.',
    },
    { id: 'openai/gpt-4o', name: '💳 GPT-4o', info: 'OpenAI multimodal.' },
    { id: 'openai/o3', name: '💳 OpenAI o3 ★', info: 'OpenAI en güçlü reasoning modeli.' },
    {
      id: 'google/gemini-2.5-pro-preview',
      name: '💳 Gemini 2.5 Pro',
      info: 'Google en güncel pro.',
    },
  ],
  gemini: [
    {
      id: 'gemini-2.5-flash-preview-05-20',
      name: 'Gemini 2.5 Flash ★Yeni ⚡',
      info: 'En güncel Flash. Hızlı + düşünme modu. Günlük kullanım.',
    },
    {
      id: 'gemini-2.5-pro-preview-05-06',
      name: 'Gemini 2.5 Pro ★En Güçlü',
      info: 'Google en güçlü modeli. Derin analiz.',
    },
    { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', info: 'Hızlı, kararlı. 1M ctx.' },
    {
      id: 'gemini-2.0-flash-lite',
      name: 'Gemini 2.0 Flash Lite ⚡',
      info: 'En ekonomik Gemini. Basit görevler.',
    },
    { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro', info: '1M token context. Uzun belgeler.' },
    { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', info: 'Hızlı ve ekonomik.' },
  ],
  anthropic: [
    {
      id: 'claude-sonnet-4-20250514',
      name: 'Claude Sonnet 4 ★',
      info: 'En güncel Claude. Dengeli güç ve hız.',
    },
    {
      id: 'claude-opus-4-20250514',
      name: 'Claude Opus 4 ★En Güçlü',
      info: 'En güçlü Claude. Derin analiz ve kodlama.',
    },
    {
      id: 'claude-haiku-4-5-20251001',
      name: 'Claude Haiku 4.5 ⚡',
      info: 'En hızlı Claude. Düşük maliyet.',
    },
    {
      id: 'claude-3-5-sonnet-20241022',
      name: 'Claude 3.5 Sonnet',
      info: 'Önceki nesil Sonnet. Kararlı.',
    },
  ],
  pollinations: [
    {
      id: 'openai',
      name: 'Pollinations OpenAI',
      info: 'Key gerektirmez. GPT tabanlı. Hızlı ve güvenilir.',
    },
    {
      id: 'mistral',
      name: 'Pollinations Mistral',
      info: 'Key gerektirmez. Mistral tabanlı. Dengeli.',
    },
    {
      id: 'llama',
      name: 'Pollinations LLaMA',
      info: 'Key gerektirmez. LLaMA tabanlı. Açık kaynak.',
    },
  ],
};

export const PREMIUM_MODELS = [
  {
    tier: 'S-Tier',
    label: '🧠 S-Tier (En İyi)',
    models: [
      { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini (OpenRouter)' },
      { id: 'google/gemini-2.5-flash', name: 'Gemini 2.5 Flash' },
      { id: 'anthropic/claude-3-haiku', name: 'Claude 3 Haiku' },
      { id: 'meta-llama/llama-4-maverick', name: 'LLaMA 4 Maverick' },
      { id: 'deepseek/deepseek-v3', name: 'DeepSeek V3' },
    ],
  },
  {
    tier: 'A-Tier',
    label: '⚡ A-Tier (Çok İyi)',
    models: [
      { id: 'nvidia/llama-3.3-nemotron-super', name: 'Nemotron Super 49B' },
      { id: 'qwen/qwen3-235b-a22b', name: 'Qwen3 235B MoE' },
      { id: 'microsoft/phi-4-reasoning-plus', name: 'Phi-4 Reasoning+' },
      { id: 'mistralai/mistral-small-3.2', name: 'Mistral Small 3.2' },
      { id: 'google/gemma-3-27b', name: 'Gemma 3 27B' },
    ],
  },
  {
    tier: 'B-Tier',
    label: '🚀 B-Tier (Hızlı)',
    models: [
      { id: 'meta-llama/llama-3.3-70b', name: 'LLaMA 3.3 70B' },
      { id: 'qwen/qwen3-32b', name: 'Qwen3 32B' },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'arcee-ai/trinity-large', name: 'Trinity Large' },
      { id: 'nousresearch/hermes-3-405b', name: 'Hermes 3 405B' },
    ],
  },
];

export const PREMIUM_INFO: Record<string, string> = {
  'openai/gpt-4o-mini': 'GPT-4o Mini — Hızlı ve yetenekli ücretsiz model. 128K ctx.',
  'google/gemini-2.5-flash': "Gemini 2.5 Flash — Google'ın en yeni hızlı modeli. Düşünme modu.",
  'anthropic/claude-3-haiku': "Claude 3 Haiku — Anthropic'in en hızlı modeli. 200K ctx.",
  'meta-llama/llama-4-maverick': "LLaMA 4 Maverick — 1M context! Meta'nın dev modeli.",
  'deepseek/deepseek-v3': 'DeepSeek V3 — 671B MoE. Kod ve analizde çok güçlü.',
  'nvidia/llama-3.3-nemotron-super': 'Nemotron Super 49B — NVIDIA fine-tune. Agentic.',
  'qwen/qwen3-235b-a22b': "Qwen3 235B MoE — Alibaba'nın dev modeli. Çok yetenekli.",
  'microsoft/phi-4-reasoning-plus': 'Phi-4 Reasoning+ — Microsoft mantık modeli.',
  'mistralai/mistral-small-3.2': 'Mistral Small 3.2 — Güncel kompakt model.',
  'google/gemma-3-27b': 'Gemma 3 27B — Google açık model. Dengeli.',
  'meta-llama/llama-3.3-70b': "LLaMA 3.3 70B — Meta'nın güçlü genel modeli.",
  'qwen/qwen3-32b': 'Qwen3 32B — Orta boy, çok yetenekli.',
  'deepseek/deepseek-r1': 'DeepSeek R1 — Chain-of-thought. Matematik harikası.',
  'arcee-ai/trinity-large': 'Trinity Large — Frontier kalite açık model.',
  'nousresearch/hermes-3-405b': 'Hermes 3 405B — 405B parametre. Dev model.',
};

export const IMAGE_MODELS: ImageModel[] = [
  { id: 'flux', name: 'Flux (Genel)', group: 'Pollinations (Ücretsiz)' },
  { id: 'flux-realism', name: 'Flux Realism (Fotoğraf)', group: 'Pollinations (Ücretsiz)' },
  { id: 'flux-pro', name: 'Flux Pro (Kalite)', group: 'Pollinations (Ücretsiz)' },
  { id: 'flux-anime', name: 'Flux Anime', group: 'Pollinations (Ücretsiz)' },
  { id: 'flux-3d', name: 'Flux 3D', group: 'Pollinations (Ücretsiz)' },
  { id: 'turbo', name: 'Turbo (Hızlı)', group: 'Pollinations (Ücretsiz)' },
  { id: 'sdxl', name: 'SDXL (Klasik)', group: 'Pollinations (Ücretsiz)' },
];

export const IMAGE_SIZES = [
  { value: '1024x1024', label: '1024×1024 (Kare)' },
  { value: '1920x1080', label: '1920×1080 (Geniş)' },
  { value: '1080x1920', label: '1080×1920 (Dikey)' },
  { value: '768x768', label: '768×768 (Küçük)' },
  { value: '1344x768', label: '1344×768 (Cinematic)' },
];

export const THEMES: ThemeConfig[] = [
  {
    id: 'dark',
    name: '🌙 Karanlık',
    icon: 'moon',
    vars: {
      '--bg': '#080c10',
      '--surface': '#0e1318',
      '--surface2': '#141b22',
      '--surface3': '#1a2330',
      '--border': '#1e2a36',
      '--border2': '#2a3a4a',
      '--border3': '#3a5066',
      '--text': '#cdd9e5',
      '--text2': '#768a9a',
      '--text3': '#4a5a6a',
      '--accent': '#58a6ff',
      '--accent2': '#79b8ff',
      '--green': '#3fb950',
      '--orange': '#f78166',
      '--yellow': '#e3b341',
      '--purple': '#bc8cff',
      '--red': '#ff6b6b',
      '--gold': '#ffd700',
      '--premium': '#ff9f43',
    },
  },
  {
    id: 'light',
    name: '☀️ Aydınlık',
    icon: 'sun',
    vars: {
      '--bg': '#f0f4f8',
      '--surface': '#ffffff',
      '--surface2': '#f5f7fa',
      '--surface3': '#e8ecf1',
      '--border': '#d0d7de',
      '--border2': '#c4cdd5',
      '--border3': '#b0bac4',
      '--text': '#1f2328',
      '--text2': '#57606a',
      '--text3': '#8c959f',
      '--accent': '#0969da',
      '--accent2': '#1a7fff',
      '--green': '#1a7f37',
      '--orange': '#cf222e',
      '--yellow': '#9a6700',
      '--purple': '#8250df',
      '--red': '#cf222e',
      '--gold': '#b8860b',
      '--premium': '#e8590c',
    },
  },
  {
    id: 'ocean',
    name: '🌊 Okyanus',
    icon: 'waves',
    vars: {
      '--bg': '#061221',
      '--surface': '#0a1a2e',
      '--surface2': '#0f2540',
      '--surface3': '#143052',
      '--border': '#1a3a5c',
      '--border2': '#214a6e',
      '--border3': '#2d5a80',
      '--text': '#c8e0f0',
      '--text2': '#7a9db8',
      '--text3': '#4a6a82',
      '--accent': '#00d4ff',
      '--accent2': '#4de0ff',
      '--green': '#00e5a0',
      '--orange': '#ff8a65',
      '--yellow': '#ffd54f',
      '--purple': '#b388ff',
      '--red': '#ff5252',
      '--gold': '#ffe082',
      '--premium': '#ffab40',
    },
  },
  {
    id: 'sunset',
    name: '🌅 Gün Batımı',
    icon: 'sunset',
    vars: {
      '--bg': '#1a0e1a',
      '--surface': '#2a1525',
      '--surface2': '#3a1e35',
      '--surface3': '#4a2845',
      '--border': '#5a3355',
      '--border2': '#6a3e65',
      '--border3': '#7a4875',
      '--text': '#f0d0e0',
      '--text2': '#b080a0',
      '--text3': '#805070',
      '--accent': '#ff6b9d',
      '--accent2': '#ff8eb0',
      '--green': '#4ade80',
      '--orange': '#fb923c',
      '--yellow': '#facc15',
      '--purple': '#c084fc',
      '--red': '#f87171',
      '--gold': '#fde047',
      '--premium': '#ff7eb3',
    },
  },
  {
    id: 'matrix',
    name: '💚 Matrix',
    icon: 'terminal',
    vars: {
      '--bg': '#000500',
      '--surface': '#001000',
      '--surface2': '#001a00',
      '--surface3': '#002400',
      '--border': '#003000',
      '--border2': '#004000',
      '--border3': '#005000',
      '--text': '#00ff41',
      '--text2': '#00cc33',
      '--text3': '#009922',
      '--accent': '#00ff41',
      '--accent2': '#33ff66',
      '--green': '#00ff00',
      '--orange': '#ff6600',
      '--yellow': '#ccff00',
      '--purple': '#cc00ff',
      '--red': '#ff0044',
      '--gold': '#ffff00',
      '--premium': '#00ff88',
    },
  },
  {
    id: 'purple',
    name: '💜 Mor Rüya',
    icon: 'sparkles',
    vars: {
      '--bg': '#0d0618',
      '--surface': '#160a25',
      '--surface2': '#1f0f35',
      '--surface3': '#281445',
      '--border': '#331955',
      '--border2': '#3d1e65',
      '--border3': '#462375',
      '--text': '#e0d0f0',
      '--text2': '#a080c0',
      '--text3': '#705090',
      '--accent': '#b388ff',
      '--accent2': '#c9a8ff',
      '--green': '#69f0ae',
      '--orange': '#ffab91',
      '--yellow': '#ffe57f',
      '--purple': '#ea80fc',
      '--red': '#ff8a80',
      '--gold': '#ffd740',
      '--premium': '#ff80ab',
    },
  },
  {
    id: 'nord',
    name: '❄️ Nord',
    icon: 'snowflake',
    vars: {
      '--bg': '#2e3440',
      '--surface': '#3b4252',
      '--surface2': '#434c5e',
      '--surface3': '#4c566a',
      '--border': '#4c566a',
      '--border2': '#5a6375',
      '--border3': '#68758a',
      '--text': '#d8dee9',
      '--text2': '#81a1c1',
      '--text3': '#616e88',
      '--accent': '#88c0d0',
      '--accent2': '#8fbcbb',
      '--green': '#a3be8c',
      '--orange': '#bf616a',
      '--yellow': '#ebcb8b',
      '--purple': '#b48ead',
      '--red': '#bf616a',
      '--gold': '#ebcb8b',
      '--premium': '#d08770',
    },
  },
];

export const API_DEFS = [
  {
    id: 'groq',
    name: 'Groq',
    keyField: 'groq',
    desc: 'Ultra-hızlı LPU çipler. LLaMA, Mixtral, DeepSeek. Ücretsiz tier çok cömert.',
    testUrl: 'https://api.groq.com/openai/v1/models',
    testHeader: (k: string) => ({ Authorization: 'Bearer ' + k }),
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    keyField: 'openrouter',
    desc: 'Tek key ile 200+ model. 25+ ücretsiz model dahil. Claude, GPT-4o, Gemini.',
    testUrl: 'https://openrouter.ai/api/v1/models',
    testHeader: (k: string) => ({ Authorization: 'Bearer ' + k }),
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    keyField: 'gemini',
    desc: 'Gemini 2.0 Flash, 2.5 Pro. Ücretsiz tier mevcut. 1M token context.',
    testUrl: (k: string) => `https://generativelanguage.googleapis.com/v1beta/models?key=${k}`,
    testHeader: () => ({}),
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    keyField: 'anthropic',
    desc: 'Claude Sonnet 4, Opus 4, Haiku 4.5. Kod ve analizde üstün.',
    testUrl: 'https://api.anthropic.com/v1/models',
    testHeader: (k: string) => ({ 'x-api-key': k, 'anthropic-version': '2023-06-01' }),
  },
];

export const QUICK_PROMPTS: QuickPrompt[] = [
  { icon: '📝', label: 'Kodu Açıkla', prompt: 'Bu kodu açıkla:\n' },
  { icon: '🌐', label: 'Çevir', prompt: 'Türkçeye çevir:\n' },
  { icon: '📋', label: 'Özetle', prompt: 'Özetle:\n' },
  { icon: '✏️', label: 'Düzelt', prompt: 'Bu metni düzelt:\n' },
  { icon: '💻', label: 'Kod Yaz', prompt: 'Şunu kodla:\n' },
  { icon: '🧪', label: 'Test Yaz', prompt: 'Birim testleri yaz:\n' },
];

export const INTENT_LABELS: Record<string, string> = {
  genel: 'Genel İyileştirme',
  ui: 'UI ve Görsel Tasarım',
  ozellik: 'Yeni Kullanıcı Özellikleri',
  performans: 'Performans Optimizasyonu',
  guvenlik: 'Güvenlik ve Gizlilik',
};

export const DEFAULT_SYSTEM_PROMPT = 'Sen yardımcı bir AI asistansın. Türkçe cevap ver.';
export const DEFAULT_PREMIUM_SYSTEM =
  'Sen premium bir AI asistansın. Detaylı ve kaliteli Türkçe cevaplar ver.';

export const STORAGE_KEYS = {
  THEME: 'aihub_theme',
  API_KEYS: 'aihub_keys',
  CHAT_SESSIONS: 'aihub_chats',
  PREMIUM_HISTORY: 'aihub_premium_chats',
  IMAGES: 'aihub_images',
  IMPROVE_HISTORY: 'aihub_improve_history',
  BACKUPS: 'aihub_backups',
  LAST_PROVIDER: 'aihub_last_provider',
  PANEL: 'aihub_panel',
};
